---

- set_fact:
    mysql_config_file: /etc/mysql/my.cnf

- name: renommage key_buffer pour éviter un warning
  replace: >
    dest={{ mysql_config_file }}
    regexp='^key_buffer[ \t]*=[ \t]*(.*)$'
    replace='key_buffer_size = \1'
  notify: restart mysql

- name: renommage key_buffer pour éviter un warning
  replace: >
    dest={{ mysql_config_file }}
    regexp='^myisam_recover[ \t]*=[ \t]*(.*)$'
    replace='myisam_recover_options = \1'
  notify: restart mysql

- name: création dossier temporaire MySQL
  file: path="{{ mysql_tmpdir }}" state=directory owner=mysql group=mysql mode=0755
    
- name: Ensure Mysql dirs exists and has ok rights
  file: path={{ item }} state=directory owner=mysql group=mysql 
  with_items: [ "{{ mysql_datadir }}", "{{ mysql_logdir }}", "{{ mysql_replogdir }}" ]

- name: Configure datadir in global MySQL configuration
  lineinfile: >
    dest={{ mysql_config_file }}
    regexp="^datadir"
    line="datadir = {{ mysql_datadir }}"
  notify: restart mysql 
  when: mysql_datadir is defined

- name: le datadir par défaut est-il encore présent
  stat: path=/var/lib/mysql
  register: old_datadir 

- name: copie des données de /var/lib/mysql vers le nouveau datadir
  shell: cp -par /var/lib/mysql/* {{ mysql_datadir }}/
  when: old_datadir.stat.exists == True

- name: reconfiguration apparmor, logrotate pour prendre en compte les nouveaux dossiers Mysql
  shell: sed -i {{ item }} -e 's#/var/lib/mysql#{{ mysql_datadir }}#g' -e 's#/var/log/mysql#{{ mysql_logdir }}#g'
  register: sedchangeconf
  changed_when: sedchangeconf.stdout != ""
  with_items: 
    - /etc/apparmor.d/usr.sbin.mysqld

- name: logrotate configuration
  template: src=templates/logrotate.j2 dest=/etc/logrotate.d/mysql-server mode=0644 owner=root group=root

- name: suppression standard dirs
  file: path={{ item }} state=absent
  with_items: 
    - /var/lib/mysql
    - /var/log/mysql

- name: fichier template master
  set_fact: 
    templateconf: "master.cnf.j2"
  when: (mysql_replication_role == 'master' or mysql_replication_role == 'master-master')
- name: fichier template slave
  set_fact: 
    templateconf: "slave.cnf.j2"
  when: (mysql_replication_role == 'slave')

- name: Install cnf override into include directory
  template: src="{{ templateconf }}"
            dest="{{ mysql_cfg_incdir }}/ansible.cnf"
            owner=0 group=mysql mode=0640
  notify: restart mysql

#sécurité, pour éviter qu'un process reste en activité et lock l'accès au dossier (rencontré lors du déploiement en preprod, avril 2016)
- name: kill mysqld
  shell: killall {{ item }}
  with_items : [ mysqld, mysqld_safe ]
  failed_when: false
  changed_when: false
  when: "{{ mysql_install_packages }} | bool"

- name: Ensure MySQL is started and not enabled on boot
  service: name={{ mysql_svc }} state=started enabled=no
  changed_when: false