---

- set_fact:
    use_debian: --defaults-file=/etc/mysql/debian.cnf

- meta: flush_handlers

- name: Disallow root login remotely
  command: 'mysql {{ use_debian }} -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Get list of hosts for the root user
  command: mysql {{ use_debian }} -NBe 'SELECT Host FROM mysql.user WHERE User = "root" ORDER BY (Host="localhost") ASC'
  register: mysql_root_hosts
  changed_when: false

- name: See if password already set
  command: mysql {{ use_debian }} -NBe 'SELECT password FROM mysql.user WHERE user = "root" and Host = "localhost"'
  register: mysql_root_password_select
  changed_when: false

# Note: We do not use mysql_user for this operation, as it doesn't always update
# the root password correctly. See: https://goo.gl/MSOejW
- name: Update MySQL root password for localhost root account
  shell: >
    mysql {{ use_debian }} -NBe
    'SET PASSWORD FOR "{{ mysql_root_username }}"@"{{ item }}" = PASSWORD("{{ mysql_root_password }}");'
  with_items: "{{ mysql_root_hosts.stdout_lines }}"
  when: not mysql_root_password_select.stdout

- name: Copy .my.cnf file with root password credentials
  template:
    src=user-my.cnf.j2
    dest={{ item }}
    owner=0 group=0 mode=0644
  with_items: 
  - "{{ mysql_user_home }}/.my.cnf"
  - /etc/mysql/conf.d/user.cnf

- name: Get list of hosts for the anonymous user
  command: mysql {{ use_debian }} -NBe 'SELECT Host FROM mysql.user WHERE User = ""'
  register: mysql_anonymous_hosts
  changed_when: false

- name: Remove anonymous MySQL users
  mysql_user:
     name: ""
     host: "{{ item }}"
     state: absent
  with_items: "{{ mysql_anonymous_hosts.stdout_lines }}"

- name: Remove MySQL test database
  mysql_db: "name='test' state=absent"
